on:
  push:
    branches: [main]
  pull_request:
    types: [closed]

jobs:
  deploy:
    if: |
      github.event_name == 'push' ||
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'deploy'))
    runs-on: ubuntu-latest
    environment: prod
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Build site
        run: docker run --rm -v $(pwd):/site ghcr.io/ravindk89/braised:latest build --config braised-prod.yaml

      - name: Deploy
        uses: burnett01/rsync-deployments@v8
        with:
          switches: --mkpath -rv --delete
          path: ./dist/
          remote_path: ${{ secrets.DEPLOY_PATH }}
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_port: ${{ secrets.DEPLOY_PORT }}
          remote_user: deploy-prod
          remote_key: ${{ secrets.DEPLOY_KEY }}
